version: "3.5"

networks:
  openstates-network:
      name: openstates-network

volumes:
  openstates-postgres:
    name: openstates-postgres

services:
  django:
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile
      args:
        UID: 1000
    volumes:
      - .:/code
    environment:
      # dev settings to reload python files when edited
      - UWSGI_PYTHON_AUTORELOAD=3
      - UWSGI_ENABLE_THREADS=1
      - DEBUG=True
      - SECRET_KEY
      - DATABASE_URL
      - CACHE_URL
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
    networks:
      - openstates-network

  nginx:
    build: docker/nginx
    ports:
      - "8000:80"
    depends_on:
      - django
    networks:
      - openstates-network

  db:
    profiles:
      - db
    image: "mdillon/postgis:11-alpine"
    environment:
      POSTGRES_PASSWORD: openstates
      POSTGRES_USER: openstates
      POSTGRES_DB: openstatesorg
      POSTGRES_HOST_AUTH_METHOD: trust
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openstates -d openstatesorg"]
      interval: 10s
      timeout: 5s
      retries: 15
    ports:
      - 5405:5432

  # webpack:
  #   build: .
  #   command: ./docker/webpack-start.sh
  #   volumes:
  #     - .:/code
